### ISSUE TITLE
Mirror website to Tor

### ISSUE THREAD

**Issue by Odyssey346** [ProjectSegfault/website#36]
We respect peoples privacy. Now it's time we respect people's anonymity. This isn't something we can "add" to the website, it has to be done server-side. I'll try to do that at least tomorrow, if I can.

**Comment by Odyssey346** [comment]
Done. Try visiting projectsegfau.lt on tor!

**Comment by kowith337** [comment]
"Your IP is kinda shit ngl"
This phrase shoved on screen while using monocles browser + orbot.

**Comment by kowith337** [comment]
"Your IP is kinda shit ngl"
This phrase shoved on screen while trying to open Nitter posts via monocles browser + orbot

**Comment by gi-yt** [comment]
we have been hit with a LOT of crawlers and bots like most working nitter instances and have had to setup IP blocklists due to that. Unfortunately well tor ips are abused a lot so can't do much about that :(

This should only happen on nitter though, we dont have blocklists or even log IPs on webserver with any other service.

**Comment by gi-yt** [comment]
PS: for such issues email us at contact@projectsegfau.lt instead, and reserve this repo for issues related to the website alone.
